mmn: main.c input_check.c methods1.c methods2.c code_translate.c inst_translate.c assistance.c project.h
	gcc -g -ansi -Wall -pedantic main.c input_check.c methods1.c methods2.c code_translate.c inst_translate.c assistance.c project.h -o mmn
